### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by Olivash** [pirtapalola/python-intermediate-rivercatchment#14]
There should be a line before this, to distinguish between the two DataArrays. This will make it more readable

https://github.com/Group3Software/python-intermediate-rivercatchment/blob/e35d0afe69fce99fc8a2df1922c787cf87f2a3b2/tests/test_models.py#L114

**Comment by pirtapalola** [comment]
2 min

**Comment by pirtapalola** [comment]
Corrected
